name: kicad-exports

on:
  push:
    paths:
    - '**.sch'
    - '**.kicad_pcb'
    - '**.yml'
  pull_request:
    paths:
      - '**.sch'
      - '**.kicad_pcb'

jobs:
  exports:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: exports
      uses: nerdyscout/kicad-exports@v2.3
      with:
        config: config/config.kibot.yml
        dir: docs
        schema: 'Controller/Controller.sch'
        board: 'Controller/Controller.kicad_pcb'
        verbose: 1
    - name: push changes to remote
      run: |
         git config --global user.name "Romaric-RILLET"
         git config --global user.email "Romaric-RILLET@users.noreply.github.com"      
         git add docs/*.pdf docs/*ibom.html
         git commit -m "github action"
         git push

